EnvironmentConfigurationMetadata:
  Description: Configuration created from the EB CLI using "eb config save".
  DateModified: '1431160226000'
  DateCreated: '1431160226000'
AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentTier:
  Name: WebServer
  Type: Standard
SolutionStack: 64bit Amazon Linux 2015.03 v1.4.1 running Multi-container Docker 1.6.0 (Generic)
OptionSettings:
  aws:ec2:vpc:
    VPCId: vpc-82c4d8e0
    AssociatePublicIpAddress: true
    Subnets: subnet-57b9b823
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    SecurityGroups: sg-4f74e22a
    EC2KeyName: aws
    InstanceType: t2.micro
  aws:elasticbeanstalk:environment:
    EnvironmentType: SingleInstance
  aws:elasticbeanstalk:sns:topics:
    Notification Endpoint: ''
